apiVersion: apps/v1
kind: Deployment
metadata:
  name: ktechnicalguftugu-springboot
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ktechnicalguftugu-springboot
  template:
    metadata:
      labels:
        app: ktechnicalguftugu-springboot
    spec:
      containers:
        - name: springboot
          image: ktechnicalguftugu/ktechnicalguftugu-docker-demo:ktechnicalguftugu-docker-demo
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: ktechnicalguftugu-springboot
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: ktechnicalguftugu-springboot
